application_server:
    resource: "@ApplicationServerBundle/Resources/config/routing.yml"
    prefix:   /

application_client:
    resource: "@ApplicationClientBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
